name: talento_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  provider: ^6.0.0
  package_info_plus: ^5.0.1
  in_app_review: ^2.0.8
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.8.0
  share_plus: ^7.2.2
  flutter_native_splash: ^2.0.0
  flutter_lints: ^5.0.0
  ## for api integration
  dio: ^5.3.2
  url_launcher: ^6.0.9
  pin_code_fields: ^8.0.0
  dotted_line: ^3.0.0
  connectivity_plus: ^5.0.2
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
#  provider: ^6.1.1
#
## For information on the generic Dart part of this file, see the
## following page: https://dart.dev/tools/pub/pubspec
#
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/animations/
    - assets/images/
    - assets/lottie/referral_animation.json
  fonts:
    - family: AnekDevanagari_Condensed
      fonts:
        - asset: assets/fonts/AnekDevanagari_Condensed-Bold.ttf
          weight: 100
        - asset: assets/fonts/AnekDevanagari_Condensed-ExtraBold.ttf
          weight: 200
        - asset: assets/fonts/AnekDevanagari_Condensed-SemiBold.ttf
          weight: 300
        - asset: assets/fonts/AnekDevanagari_Condensed-Light.ttf
          weight: 400
        - asset: assets/fonts/AnekDevanagari_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/AnekDevanagari_Condensed-Regular.ttf
          weight: 600
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_native_splash:
  color: "#fce1aa"
  image: assets/images/handshake.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/handshake.png"